-- Generated by Oracle SQL Developer Data Modeler 4.1.1.888
--   at:        2015-10-23 22:45:43 AEDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




DROP TABLE branch CASCADE CONSTRAINTS ;

DROP TABLE certificate CASCADE CONSTRAINTS ;

DROP TABLE customer CASCADE CONSTRAINTS ;

DROP TABLE department CASCADE CONSTRAINTS ;

DROP TABLE employee CASCADE CONSTRAINTS ;

DROP TABLE employee_certificate CASCADE CONSTRAINTS ;

DROP TABLE employee_qualification CASCADE CONSTRAINTS ;

DROP TABLE manufacturer CASCADE CONSTRAINTS ;

DROP TABLE model CASCADE CONSTRAINTS ;

DROP TABLE parts CASCADE CONSTRAINTS ;

DROP TABLE payment CASCADE CONSTRAINTS ;

DROP TABLE previousOwner CASCADE CONSTRAINTS ;

DROP TABLE qualification CASCADE CONSTRAINTS ;

DROP TABLE sales CASCADE CONSTRAINTS ;

DROP TABLE sales_payment CASCADE CONSTRAINTS ;

DROP TABLE sales_vehicle CASCADE CONSTRAINTS ;

DROP TABLE secondhand_vehicle CASCADE CONSTRAINTS ;

DROP TABLE supplier CASCADE CONSTRAINTS ;

DROP TABLE supplier_manufacturer CASCADE CONSTRAINTS ;

DROP TABLE testDrive CASCADE CONSTRAINTS ;

DROP TABLE valuation CASCADE CONSTRAINTS ;

DROP TABLE valuation_parts CASCADE CONSTRAINTS ;

DROP TABLE vehicle CASCADE CONSTRAINTS ;

CREATE TABLE branch
  (
    branchID     NUMBER (8) NOT NULL ,
    employeeID   CHAR (6) NOT NULL ,
    location     VARCHAR2 (15) NOT NULL ,
    address      VARCHAR2 (50) NOT NULL ,
    phone        NUMBER (10) NOT NULL ,
    tradingHours DATE NOT NULL ,
    description  VARCHAR2 (50)
  ) ;
CREATE UNIQUE INDEX branch__IDX ON branch
  (
    employeeID ASC
  )
  ;
ALTER TABLE branch ADD CONSTRAINT branch_PK PRIMARY KEY ( branchID ) ;


CREATE TABLE certificate
  (
    certificateID          NUMBER (8) NOT NULL ,
    certificateDescription VARCHAR2 (30) NOT NULL ,
    dateAchieved           DATE NOT NULL
  ) ;
ALTER TABLE certificate ADD CONSTRAINT certificate_PK PRIMARY KEY ( certificateID ) ;


CREATE TABLE customer
  (
    customerNumber           CHAR (7) NOT NULL ,
    title                    CHAR (5) NOT NULL ,
    customerFirstName        VARCHAR2 (20) NOT NULL ,
    customerLastName         VARCHAR2 (20) NOT NULL ,
    customerAddress          VARCHAR2 (50) NOT NULL ,
    customerEmailAddress     VARCHAR2 (50) NOT NULL ,
    customerMobileNumber     NUMBER (10) NOT NULL ,
    licenseNumber            VARCHAR2 (15) NOT NULL ,
    numberOfVehiclePurchased NUMBER (3) NOT NULL
  ) ;
ALTER TABLE customer ADD CONSTRAINT customer_PK PRIMARY KEY ( customerNumber ) ;


CREATE TABLE department
  (
    departmentID       NUMBER (8) NOT NULL ,
    branchID           NUMBER (8) NOT NULL ,
    departmentName     VARCHAR2 (25) NOT NULL ,
    departmentPhone    NUMBER (10) NOT NULL ,
    departmentType     VARCHAR2 (20) NOT NULL ,
    departmentPostcode VARCHAR2 (10)
  ) ;
ALTER TABLE department ADD CONSTRAINT department_PK PRIMARY KEY ( departmentID ) ;


CREATE TABLE employee
  (
    employeeID           CHAR (6) NOT NULL ,
    departmentID         NUMBER (8) NOT NULL ,
    branchID             NUMBER (8) NOT NULL ,
    employeeFirstName    VARCHAR2 (20) NOT NULL ,
    employeeLastName     VARCHAR2 (20) NOT NULL ,
    employeePosition     VARCHAR2 (20) NOT NULL ,
    employeeSalary       NUMBER (10) NOT NULL ,
    employeeAddress      VARCHAR2 (50) NOT NULL ,
    employeeMobileNumber NUMBER (10) NOT NULL ,
    workLoad             CHAR (10) NOT NULL
  ) ;
CREATE UNIQUE INDEX employee__IDX ON employee
  (
    branchID ASC
  )
  ;
ALTER TABLE employee ADD CONSTRAINT employee_PK PRIMARY KEY ( employeeID ) ;


CREATE TABLE employee_certificate
  (
    certificateID NUMBER (8) NOT NULL ,
    employeeID    CHAR (6) NOT NULL
  ) ;
ALTER TABLE employee_certificate ADD CONSTRAINT employee_certificate_PK PRIMARY KEY ( certificateID, employeeID ) ;


CREATE TABLE employee_qualification
  (
    qualificationID NUMBER (8) NOT NULL ,
    employeeID      CHAR (6) NOT NULL
  ) ;
ALTER TABLE employee_qualification ADD CONSTRAINT employee_qualification_PK PRIMARY KEY ( qualificationID, employeeID ) ;


CREATE TABLE manufacturer
  (
    manufacturerID   NUMBER (8) NOT NULL ,
    manufacturerName VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE manufacturer ADD CONSTRAINT manufacturer_PK PRIMARY KEY ( manufacturerID ) ;


CREATE TABLE model
  (
    modelID          NUMBER (8) NOT NULL ,
    manufacturerID   NUMBER (8) NOT NULL ,
    colour           VARCHAR2 (15) NOT NULL ,
    engineSize       VARCHAR2 (15) NOT NULL ,
    engineType       VARCHAR2 (15) NOT NULL ,
    stereoType       VARCHAR2 (15) NOT NULL ,
    airconditioning  VARCHAR2 (15) NOT NULL ,
    powerSteering    VARCHAR2 (15) ,
    transmissionType VARCHAR2 (10) NOT NULL
  ) ;
ALTER TABLE model ADD CONSTRAINT model_PK PRIMARY KEY ( modelID ) ;


CREATE TABLE parts
  (
    partsID    NUMBER (8) NOT NULL ,
    supplierID NUMBER (8) NOT NULL ,
    partName   VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE parts ADD CONSTRAINT parts_PK PRIMARY KEY ( partsID ) ;


CREATE TABLE payment
  (
    paymentID     CHAR (9) NOT NULL ,
    salesNumber   NUMBER (8) NOT NULL ,
    paymentDate   DATE NOT NULL ,
    paymentTime   DATE NOT NULL ,
    paymentAmount NUMBER (10) NOT NULL ,
    paymentType   VARCHAR2 (10) NOT NULL
  ) ;
CREATE UNIQUE INDEX payment__IDX ON payment
  (
    salesNumber ASC
  )
  ;
ALTER TABLE payment ADD CONSTRAINT payment_PK PRIMARY KEY ( paymentID ) ;


CREATE TABLE previousOwner
  (
    previousOwnerID   NUMBER (8) NOT NULL ,
    title             CHAR (5) NOT NULL ,
    ownerFirstName    VARCHAR2 (20) NOT NULL ,
    ownerLastName     VARCHAR2 (20) NOT NULL ,
    ownerAddress      VARCHAR2 (50) NOT NULL ,
    ownerMobileNumber NUMBER (10) NOT NULL ,
    licenseNumber     VARCHAR2 (15) NOT NULL
  ) ;
ALTER TABLE previousOwner ADD CONSTRAINT number_of_previous_owner_PK PRIMARY KEY ( previousOwnerID ) ;


CREATE TABLE qualification
  (
    qualificationID          NUMBER (8) NOT NULL ,
    qualificationDescription VARCHAR2 (30) NOT NULL ,
    dateAchieved             DATE NOT NULL
  ) ;
ALTER TABLE qualification ADD CONSTRAINT qualification_PK PRIMARY KEY ( qualificationID ) ;


CREATE TABLE sales
  (
    salesNumber    NUMBER (8) NOT NULL ,
    salesDate      DATE NOT NULL ,
    salesTime      DATE NOT NULL ,
    employeeID     CHAR (6) NOT NULL ,
    commission     NUMBER (6) ,
    salesAmount    NUMBER (10) NOT NULL ,
    amountDue      NUMBER (10) NOT NULL ,
    customerNumber CHAR (7) NOT NULL
  ) ;
ALTER TABLE sales ADD CONSTRAINT sales_PK PRIMARY KEY ( salesNumber ) ;


CREATE TABLE sales_payment
  (
    salesNumber NUMBER (8) NOT NULL ,
    paymentID   CHAR (9) NOT NULL
  ) ;
CREATE UNIQUE INDEX sales_payment__IDX ON sales_payment
  (
    paymentID ASC
  )
  ;
ALTER TABLE sales_payment ADD CONSTRAINT sales_payment_PK PRIMARY KEY ( salesNumber ) ;


CREATE TABLE sales_vehicle
  (
    salesNumber NUMBER (8) NOT NULL ,
    regNumber   CHAR (6) NOT NULL
  ) ;
ALTER TABLE sales_vehicle ADD CONSTRAINT sales_vehicle_PK PRIMARY KEY ( salesNumber, regNumber ) ;


CREATE TABLE secondhand_vehicle
  (
    secondhand_vehicleID     NUMBER (8) NOT NULL ,
    regNumber                CHAR (6) NOT NULL ,
    modelID                  NUMBER (8) NOT NULL ,
    dateAcquired             DATE NOT NULL ,
    previousOwnerID          NUMBER (8) NOT NULL ,
    odometerDistance         VARCHAR2 (6) NOT NULL ,
    engineNumber             NUMBER (8) NOT NULL ,
    bodyIdentificationNumber NUMBER (8) NOT NULL ,
    amountPaid               NUMBER (10) NOT NULL
  ) ;
ALTER TABLE secondhand_vehicle ADD CONSTRAINT secondhand_vehicle_PK PRIMARY KEY ( secondhand_vehicleID ) ;


CREATE TABLE supplier
  (
    supplierID   NUMBER (8) NOT NULL ,
    supplierName VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE supplier ADD CONSTRAINT supplier_PK PRIMARY KEY ( supplierID ) ;


CREATE TABLE supplier_manufacturer
  (
    supplierID     NUMBER (8) NOT NULL ,
    manufacturerID NUMBER (8) NOT NULL
  ) ;
ALTER TABLE supplier_manufacturer ADD CONSTRAINT supplier_manufacturer_PK PRIMARY KEY ( supplierID, manufacturerID ) ;


CREATE TABLE testDrive
  (
    testDriveID       NUMBER (8) NOT NULL ,
    regNumber         CHAR (6) NOT NULL ,
    customerNumber    CHAR (7) NOT NULL ,
    customerFirstName VARCHAR2 (20) NOT NULL ,
    customerLastName  VARCHAR2 (20) NOT NULL ,
    licenseNumber     VARCHAR2 (15) NOT NULL ,
    loanTime          DATE NOT NULL ,
    returnTime        DATE NOT NULL
  ) ;
ALTER TABLE testDrive ADD CONSTRAINT testDrive_PK PRIMARY KEY ( testDriveID ) ;


CREATE TABLE valuation
  (
    valuationID            NUMBER (8) NOT NULL ,
    employeeID             CHAR (6) NOT NULL ,
    secondhand_vehicleID   NUMBER (8) NOT NULL ,
    costForSalability      NUMBER (10) NOT NULL ,
    registrationExpiryDate DATE NOT NULL ,
    profitAmount           NUMBER (10) NOT NULL
  ) ;
ALTER TABLE valuation ADD CONSTRAINT valuation_PK PRIMARY KEY ( valuationID ) ;


CREATE TABLE valuation_parts
  (
    partsID     NUMBER (8) NOT NULL ,
    valuationID NUMBER (8) NOT NULL
  ) ;
ALTER TABLE valuation_parts ADD CONSTRAINT valuation_parts_PK PRIMARY KEY ( partsID, valuationID ) ;


CREATE TABLE vehicle
  (
    regNumber              CHAR (6) NOT NULL ,
    branchID               NUMBER (8) NOT NULL ,
    VIN                    CHAR (10) NOT NULL ,
    odometerNumber         VARCHAR2 (6) NOT NULL ,
    modelID                NUMBER (8) NOT NULL ,
    purchasePrice          NUMBER (10) NOT NULL ,
    recommendedPrice       NUMBER (10) NOT NULL ,
    minimumPrice           NUMBER (10) NOT NULL ,
    yearOfManufacture      DATE NOT NULL ,
    numberOfPreviousOwners NUMBER (3) NOT NULL
  ) ;
ALTER TABLE vehicle ADD CONSTRAINT vehicle_PK PRIMARY KEY ( regNumber ) ;


ALTER TABLE department ADD CONSTRAINT branch_department FOREIGN KEY ( branchID ) REFERENCES branch ( branchID ) ;

ALTER TABLE employee_certificate ADD CONSTRAINT certificate_employee FOREIGN KEY ( certificateID ) REFERENCES certificate ( certificateID ) ;

ALTER TABLE sales ADD CONSTRAINT customer_sales FOREIGN KEY ( customerNumber ) REFERENCES customer ( customerNumber ) ;

ALTER TABLE employee_certificate ADD CONSTRAINT employee_certificate FOREIGN KEY ( employeeID ) REFERENCES employee ( employeeID ) ;

ALTER TABLE employee ADD CONSTRAINT employee_department FOREIGN KEY ( departmentID ) REFERENCES department ( departmentID ) ;

ALTER TABLE branch ADD CONSTRAINT employee_manager_branch FOREIGN KEY ( employeeID ) REFERENCES employee ( employeeID ) ;

ALTER TABLE employee ADD CONSTRAINT employee_manager_branchv1 FOREIGN KEY ( branchID ) REFERENCES branch ( branchID ) ;

ALTER TABLE employee_qualification ADD CONSTRAINT employee_qualification FOREIGN KEY ( qualificationID ) REFERENCES qualification ( qualificationID ) ;

ALTER TABLE employee_qualification ADD CONSTRAINT employee_qualificationv1 FOREIGN KEY ( employeeID ) REFERENCES employee ( employeeID ) ;

ALTER TABLE sales ADD CONSTRAINT employee_sales FOREIGN KEY ( employeeID ) REFERENCES employee ( employeeID ) ;

ALTER TABLE valuation ADD CONSTRAINT "employee_valuation(mechanic)" FOREIGN KEY ( employeeID ) REFERENCES employee ( employeeID ) ;

ALTER TABLE model ADD CONSTRAINT manufacturer_model FOREIGN KEY ( manufacturerID ) REFERENCES manufacturer ( manufacturerID ) ;

ALTER TABLE vehicle ADD CONSTRAINT model_vehicle FOREIGN KEY ( modelID ) REFERENCES model ( modelID ) ;

ALTER TABLE parts ADD CONSTRAINT part_supplier FOREIGN KEY ( supplierID ) REFERENCES supplier ( supplierID ) ;

ALTER TABLE valuation_parts ADD CONSTRAINT parts_valuation FOREIGN KEY ( partsID ) REFERENCES parts ( partsID ) ;

ALTER TABLE secondhand_vehicle ADD CONSTRAINT prevOwner_2ndhandvehicle FOREIGN KEY ( previousOwnerID ) REFERENCES previousOwner ( previousOwnerID ) ;

ALTER TABLE sales_payment ADD CONSTRAINT sales_payment FOREIGN KEY ( paymentID ) REFERENCES payment ( paymentID ) ;

ALTER TABLE payment ADD CONSTRAINT sales_paymentv1 FOREIGN KEY ( salesNumber ) REFERENCES sales_payment ( salesNumber ) ;

ALTER TABLE sales_payment ADD CONSTRAINT sales_paymentv1v1 FOREIGN KEY ( salesNumber ) REFERENCES sales ( salesNumber ) ;

ALTER TABLE sales_vehicle ADD CONSTRAINT sales_vehicle FOREIGN KEY ( regNumber ) REFERENCES vehicle ( regNumber ) ;

ALTER TABLE sales_vehicle ADD CONSTRAINT sales_vehiclev1 FOREIGN KEY ( salesNumber ) REFERENCES sales ( salesNumber ) ;

ALTER TABLE secondhand_vehicle ADD CONSTRAINT secondhandcarvehicle_model FOREIGN KEY ( modelID ) REFERENCES model ( modelID ) ;

ALTER TABLE supplier_manufacturer ADD CONSTRAINT supplier_manufacturerv1 FOREIGN KEY ( supplierID ) REFERENCES supplier ( supplierID ) ;

ALTER TABLE supplier_manufacturer ADD CONSTRAINT supplier_manufacturerv2 FOREIGN KEY ( manufacturerID ) REFERENCES manufacturer ( manufacturerID ) ;

ALTER TABLE testDrive ADD CONSTRAINT testDrive_customer FOREIGN KEY ( customerNumber ) REFERENCES customer ( customerNumber ) ;

ALTER TABLE testDrive ADD CONSTRAINT testDrive_vehicle FOREIGN KEY ( regNumber ) REFERENCES vehicle ( regNumber ) ;

ALTER TABLE valuation_parts ADD CONSTRAINT valuation_parts FOREIGN KEY ( valuationID ) REFERENCES valuation ( valuationID ) ;

ALTER TABLE valuation ADD CONSTRAINT valuation_secondhandvehicle FOREIGN KEY ( secondhand_vehicleID ) REFERENCES secondhand_vehicle ( secondhand_vehicleID ) ;

ALTER TABLE vehicle ADD CONSTRAINT vehicle_branch FOREIGN KEY ( branchID ) REFERENCES branch ( branchID ) ;

ALTER TABLE secondhand_vehicle ADD CONSTRAINT vehicle_secondhandvehicle FOREIGN KEY ( regNumber ) REFERENCES vehicle ( regNumber ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            23
-- CREATE INDEX                             4
-- ALTER TABLE                             53
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
